name: Create icon font

on:
  workflow_dispatch:

jobs: 
  create_icon_font:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install
        working-directory: ./importer
  
      - name: Convert icons to font
        run: npm run create-icon-font
        working-directory: ./importer
        env:
          PAT: ${{ secrets.AUTOMATION_PAT }}
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'feat: Update icon font'
          title: 'feat: Update icon font'
          branch: update-icon-font
