name: Create icon font

on:
  workflow_dispatch:

jobs: 
  create_icon_font:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Fetch icons from moon-icons-base repository
        run: |
          git clone --depth 1 https://github.com/coingaming/moon-icons-base.git temp_repo
          cp -r temp_repo/icons/* ./svgs/
          rm -rf temp_repo
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'feat: Update icon font'
          title: 'feat: Update icon font'
          branch: update-icon-font
