name: Create icon font

# Used to allow moon-icons-base workflow to trigger this workflow and also manual triggering.
on:
  workflow_dispatch:

# So only the latest run is executed. Used to avoid concurrency issues as Figma webhook can be spammy at times.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs: 
  create_icon_font:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 21
  
      - name: Convert icons to font
        run: npm run create-icon-font
        working-directory: ./importer

      - name: Generate Dart classes
        run: npm run convert-css-to-dart
        working-directory: ./importer
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'feat: 🤖 ${{ github.event.client_payload.description }}'
          title: 'feat: 🤖 ${{ github.event.client_payload.description }}'
          branch: update-icon-font
