name: Publish to pub.dev

on:
  #push:
    #branches:
      #- main

  # Allow manual triggering of the workflow.
  workflow_dispatch:

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    # if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    permissions:
      id-token: write # Required for authentication using OIDC

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1